<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            ['name' => 'Badakhshan', 'country_id' => 1],
            ['name' => 'Badghis', 'country_id' => 1],
            ['name' => 'Baghlan', 'country_id' => 1],
            ['name' => 'Balkh', 'country_id' => 1],
            ['name' => 'Bamyan', 'country_id' => 1],
            ['name' => 'Daykundi', 'country_id' => 1],
            ['name' => 'Farah', 'country_id' => 1],
            ['name' => 'Faryab', 'country_id' => 1],
            ['name' => 'Ghazni', 'country_id' => 1],
            ['name' => 'Ghor', 'country_id' => 1],
            ['name' => 'Helmand', 'country_id' => 1],
            ['name' => 'Herat', 'country_id' => 1],
            ['name' => 'Jowzjan', 'country_id' => 1],
            ['name' => 'Kabul', 'country_id' => 1],
            ['name' => 'Kandahar', 'country_id' => 1],
            ['name' => 'Kapisa', 'country_id' => 1],
            ['name' => 'Khost', 'country_id' => 1],
            ['name' => 'Kunar', 'country_id' => 1],
            ['name' => 'Kunduz', 'country_id' => 1],
            ['name' => 'Laghman', 'country_id' => 1],
            ['name' => 'Logar', 'country_id' => 1],
            ['name' => 'Nangarhar', 'country_id' => 1],
            ['name' => 'Nimroz', 'country_id' => 1],
            ['name' => 'Nuristan', 'country_id' => 1],
            ['name' => 'Paktia', 'country_id' => 1],
            ['name' => 'Paktika', 'country_id' => 1],
            ['name' => 'Panjshir', 'country_id' => 1],
            ['name' => 'Parwan', 'country_id' => 1],
            ['name' => 'Samangan', 'country_id' => 1],
            ['name' => 'Sar-e Pol', 'country_id' => 1],
            ['name' => 'Takhar', 'country_id' => 1],
            ['name' => 'Urozgan', 'country_id' => 1],
            ['name' => 'Wardak', 'country_id' => 1],
            ['name' => 'Zabul', 'country_id' => 1],
            ['name' => 'Berat', 'country_id' => 2], // assuming Albania's country_id is 2
            ['name' => 'Dibër', 'country_id' => 2],
            ['name' => 'Durrës', 'country_id' => 2],
            ['name' => 'Elbasan', 'country_id' => 2],
            ['name' => 'Fier', 'country_id' => 2],
            ['name' => 'Gjirokastër', 'country_id' => 2],
            ['name' => 'Korçë', 'country_id' => 2],
            ['name' => 'Kukës', 'country_id' => 2],
            ['name' => 'Lezhë', 'country_id' => 2],
            ['name' => 'Shkodër', 'country_id' => 2],
            ['name' => 'Tirana', 'country_id' => 2],
            ['name' => 'Vlorë', 'country_id' => 2],
            ['name' => 'Adrar', 'country_id' => 3], // assuming Algeria's country_id is 3
            ['name' => 'Chlef', 'country_id' => 3],
            ['name' => 'Laghouat', 'country_id' => 3],
            ['name' => 'Oum El Bouaghi', 'country_id' => 3],
            ['name' => 'Batna', 'country_id' => 3],
            ['name' => 'Béjaïa', 'country_id' => 3],
            ['name' => 'Biskra', 'country_id' => 3],
            ['name' => 'Béchar', 'country_id' => 3],
            ['name' => 'Blida', 'country_id' => 3],
            ['name' => 'Bouira', 'country_id' => 3],
            ['name' => 'Tamanghasset', 'country_id' => 3],
            ['name' => 'Tébessa', 'country_id' => 3],
            ['name' => 'Tlemcen', 'country_id' => 3],
            ['name' => 'Tiaret', 'country_id' => 3],
            ['name' => 'Tizi Ouzou', 'country_id' => 3],
            ['name' => 'Algiers', 'country_id' => 3],
            ['name' => 'Djelfa', 'country_id' => 3],
            ['name' => 'Jijel', 'country_id' => 3],
            ['name' => 'Sétif', 'country_id' => 3],
            ['name' => 'Saïda', 'country_id' => 3],
            ['name' => 'Skikda', 'country_id' => 3],
            ['name' => 'Sidi Bel Abbès', 'country_id' => 3],
            ['name' => 'Annaba', 'country_id' => 3],
            ['name' => 'Guelma', 'country_id' => 3],
            ['name' => 'Constantine', 'country_id' => 3],
            ['name' => 'Médéa', 'country_id' => 3],
            ['name' => 'Mostaganem', 'country_id' => 3],
            ['name' => 'M’Sila', 'country_id' => 3],
            ['name' => 'Mascara', 'country_id' => 3],
            ['name' => 'Ouargla', 'country_id' => 3],
            ['name' => 'Oran', 'country_id' => 3],
            ['name' => 'El Bayadh', 'country_id' => 3],
            ['name' => 'Illizi', 'country_id' => 3],
            ['name' => 'Bordj Bou Arréridj', 'country_id' => 3],
            ['name' => 'Boumerdès', 'country_id' => 3],
            ['name' => 'El Tarf', 'country_id' => 3],
            ['name' => 'Tindouf', 'country_id' => 3],
            ['name' => 'Tissemsilt', 'country_id' => 3],
            ['name' => 'El Oued', 'country_id' => 3],
            ['name' => 'Khenchela', 'country_id' => 3],
            ['name' => 'Souk Ahras', 'country_id' => 3],
            ['name' => 'Tipasa', 'country_id' => 3],
            ['name' => 'Mila', 'country_id' => 3],
            ['name' => 'Aïn Defla', 'country_id' => 3],
            ['name' => 'Naâma', 'country_id' => 3],
            ['name' => 'Aïn Témouchent', 'country_id' => 3],
            ['name' => 'Ghardaïa', 'country_id' => 3],
            ['name' => 'Relizane', 'country_id' => 3],
            ['name' => 'Andorra la Vella', 'country_id' => 4], // assuming Andorra's country_id is 4
            ['name' => 'Canillo', 'country_id' => 4],
            ['name' => 'Encamp', 'country_id' => 4],
            ['name' => 'Escaldes-Engordany', 'country_id' => 4],
            ['name' => 'La Massana', 'country_id' => 4],
            ['name' => 'Ordino', 'country_id' => 4],
            ['name' => 'Sant Julià de Lòria', 'country_id' => 4],
            ['name' => 'Bengo', 'country_id' => 5], // assuming Angola's country_id is 5
            ['name' => 'Benguela', 'country_id' => 5],
            ['name' => 'Bié', 'country_id' => 5],
            ['name' => 'Cabinda', 'country_id' => 5],
            ['name' => 'Cuando Cubango', 'country_id' => 5],
            ['name' => 'Cuanza Norte', 'country_id' => 5],
            ['name' => 'Cuanza Sul', 'country_id' => 5],
            ['name' => 'Cunene', 'country_id' => 5],
            ['name' => 'Huambo', 'country_id' => 5],
            ['name' => 'Huíla', 'country_id' => 5],
            ['name' => 'Luanda', 'country_id' => 5],
            ['name' => 'Lunda Norte', 'country_id' => 5],
            ['name' => 'Lunda Sul', 'country_id' => 5],
            ['name' => 'Malanje', 'country_id' => 5],
            ['name' => 'Moxico', 'country_id' => 5],
            ['name' => 'Namibe', 'country_id' => 5],
            ['name' => 'Uíge', 'country_id' => 5],
            ['name' => 'Zaire', 'country_id' => 5],
            ['name' => 'Saint George', 'country_id' => 6], // assuming Antigua and Barbuda's country_id is 6
            ['name' => 'Saint John', 'country_id' => 6],
            ['name' => 'Saint Mary', 'country_id' => 6],
            ['name' => 'Saint Paul', 'country_id' => 6],
            ['name' => 'Saint Peter', 'country_id' => 6],
            ['name' => 'Saint Philip', 'country_id' => 6],
            ['name' => 'Barbuda', 'country_id' => 6],
            ['name' => 'Buenos Aires', 'country_id' => 7],
            ['name' => 'Catamarca', 'country_id' => 7],
            ['name' => 'Chaco', 'country_id' => 7],
            ['name' => 'Chubut', 'country_id' => 7],
            ['name' => 'Córdoba', 'country_id' => 7],
            ['name' => 'Corrientes', 'country_id' => 7],
            ['name' => 'Entre Ríos', 'country_id' => 7],
            ['name' => 'Formosa', 'country_id' => 7],
            ['name' => 'Jujuy', 'country_id' => 7],
            ['name' => 'La Pampa', 'country_id' => 7],
            ['name' => 'La Rioja', 'country_id' => 7],
            ['name' => 'Mendoza', 'country_id' => 7],
            ['name' => 'Misiones', 'country_id' => 7],
            ['name' => 'Neuquén', 'country_id' => 7],
            ['name' => 'Río Negro', 'country_id' => 7],
            ['name' => 'Salta', 'country_id' => 7],
            ['name' => 'San Juan', 'country_id' => 7],
            ['name' => 'San Luis', 'country_id' => 7],
            ['name' => 'Santa Cruz', 'country_id' => 7],
            ['name' => 'Santa Fe', 'country_id' => 7],
            ['name' => 'Santiago del Estero', 'country_id' => 7],
            ['name' => 'Tierra del Fuego', 'country_id' => 7],
            ['name' => 'Tucumán', 'country_id' => 7],
            ['name' => 'Ciudad Autónoma de Buenos Aires', 'country_id' => 7], // Buenos Aires Capital

        ];

        DB::table('states')->insert($states);
    }
}
